#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xrdb -load $HOME/.config/.Xresources &
picom &
feh --bg-fill ~/Pictures/purple-wp.png &
xrandr --output eDP1 --brightness 0.5 &         # super + alt + r reset bswpm voor andere helderheidr
polybar music &
polybar other &
polybar bspwm &

bspc monitor -d I II III IV V


bspc config border_width         0
bspc config window_gap          16

bspc config split_ratio          0.6
bspc config top_padding 34
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
